print("Itsy bitsy spider\nwent up the water spout")
print()
print("My", "name", "is", "Monty", "Python", sep="-")
print()
print("My name is", end=" ")
print("Monty Python")
print()
print("My name is ", end="")
print("Filip")